# Dockerfile pour le développement (avec hot reload)
FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Variable d'environnement
ENV NODE_ENV=development

# Démarrer le serveur de dev NestJS (hot reload)
CMD ["npm", "run", "start:dev"]
